import type { Metadata } from "next";
import "./globals.css";
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import localFont from 'next/font/local';
import TopButton from '@/components/TopButton';
import DarkModeButton from '@/components/DarkModeButton';
import DarkModeContextProvider from '@/context/DarkModeContext';

const pretendard = localFont({
  src: [
    {
      path: '../fonts/Pretendard-Regular.woff2',
      weight: '400'
    },
    {
      path: '../fonts/Pretendard-SemiBold.woff2',
      weight: '600'
    },
    {
      path: '../fonts/Pretendard-Bold.woff2',
      weight: '700'
    },
    {
      path: '../fonts/Pretendard-ExtraBold.woff2',
      weight: '800'
    }
  ],
  display: 'swap',
  weight: '45 920',
})
export const metadata: Metadata = {
  title: "Pyeon So Yeong homepage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={pretendard.className}>
      <body className='flex flex-col w-full mx-auto'>
        <DarkModeContextProvider>
          <Header />
          <main className='grow'>
            {/* flex 중간 꽉채우기.. -> flex 자식요소 flex-grow :1 or flex: 1 1 auto (flex-auto) */}
            {children}
          </main>
          <Footer />
          <DarkModeButton />
          <TopButton />
        </DarkModeContextProvider>
        <div id="portal" />
      </body>
    </html>
  );
}
