import type { Metadata } from "next";
import "./globals.css";
import Header from '@/components/Header';

import { Noto_Sans_KR } from 'next/font/google';
import Footer from '@/components/Footer';

const sans = Noto_Sans_KR({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={sans.className}>
      <body className='flex flex-col w-full mx-auto'>
        <Header />
        <main className='grow'>
          {/* flex 중간 꽉채우기.. -> flex 자식요소 flex-grow :1 or flex: 1 1 auto (flex-auto) */}
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
